<a href="https://colab.research.google.com/github/jgerdes2021/Gerdes_Probability_Statistics-Fall-2022/blob/main/Jenny_Gerdes_Stats_2022_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook #3

# Loops

In [1]:
for i in range(10): 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
  print(i)

5
6
7


In [3]:
for i in range(3):
    print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [55]:
#Test numbers

# Functions

In [4]:
def square(x): 
  return x**2

In [56]:
#x**2 is x squared

In [5]:
square(5)

25

In [60]:
#The square root of 25 is 5

In [6]:
square(square(2))

16

In [7]:
square(square(square(2)))

256

In [8]:
square(6)

36

In [59]:
#The square root of 36 is 6

In [9]:
square(123456)

15241383936

In [10]:
square(square(5))

625

In [11]:
def add_two(x): 
  return x+2

In [12]:
add_two(5)

7

In [13]:
square(add_two(5))

49

# Logical Branching

In [14]:
choice = "apple"

In [15]:
if choice == "apple": 
    print("You chose apples.")

else: 

      print("You did not chose apples")

You chose apples.


In [61]:
#It tells you what text you said

In [16]:
choice = "orange"

In [17]:
if choice == "apple": 

  print("You chose apples.")
  print("Thank you, shop again!")

elif choice == "orange": 

  print("You chose oranges.") 
  print("Thank you, shop again!")

else: 

  print("You did not chose apples or oranges.") 
  print("Thank you, shop again!")

You chose oranges.
Thank you, shop again!


In [62]:
#It writes out the text stated

# User Input

In [18]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): 


In [19]:
choice 

''

# Speed Test 

In [20]:
import numpy as np

In [21]:
np.random.permutation(52)

array([47, 22, 39, 12, 41, 44, 50, 36, 30, 15, 46, 40,  7,  0, 43, 33, 16,
       27,  8, 11, 38,  5, 14, 17, 45, 24, 13, 26,  4, 18, 10, 42, 48, 32,
       31,  9, 49,  1, 37, 21, 23,  2, 29, 20, 51, 28, 34, 25, 35, 19,  3,
        6])

In [63]:
#np.random.permutations states random numbers

In [22]:
cards = np.random.permutation(52)

In [23]:
cards

array([22,  9, 17, 34, 51, 37, 44,  5,  3, 45,  7, 38, 21, 25, 12, 43,  8,
       48, 19, 32, 13,  1, 27, 31, 29, 20, 18, 46, 50,  4,  0, 30,  6, 41,
       33, 40, 35, 15, 16, 42, 14, 10,  2, 49, 47, 39, 36, 23, 24, 26, 11,
       28])

In [24]:
cards[0]

22

In [25]:
cards[1]

9

In [26]:
cards[2]

17

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [65]:
#It will display cards

In [27]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [28]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [29]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [30]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two', 'Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [31]:
def card_name(card_number): 

  suit = card_number//13
  name = card_number%13

  return names[name] + " of " + suits[suit]

In [32]:
card_name(0)

'Ace of Clubs'

In [67]:
#It displays the card names

In [33]:
card_name(51)

'King of Diamonds'

In [34]:
cards = np.random.permutation(52)

In [35]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [68]:
#It shows the cards throughout the deck

In [36]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Five of Spades', 'Three of Clubs', 'Eight of Hearts')

In [37]:
for i in range(5): 
    print(card_name(cards[i]))

Five of Spades
Three of Clubs
Jack of Spades
Eight of Spades
Six of Diamonds


In [38]:
for i in range(15): 
    print(card_name(cards[i]))

Five of Spades
Three of Clubs
Jack of Spades
Eight of Spades
Six of Diamonds
Ace of Clubs
King of Spades
Jack of Diamonds
Nine of Hearts
Queen of Hearts
Queen of Spades
Five of Diamonds
Three of Spades
Two of Clubs
Ace of Diamonds


In [39]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [40]:
suit = ['k','p','s','1']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [41]:
i = np.random.randint(4)
j = np.random.randint(13)

In [42]:
i,j

(3, 9)

In [43]:
suit[i]

'1'

In [44]:
card[i]

'4'

In [45]:
from IPython.core.display import display, HTML

In [50]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [51]:
card_image(3)

'k4'

In [52]:
img = card_url_head + card_image(3) + card_url_tail

In [53]:
show_img(img)

In [70]:
#It shows the image of the card

In [54]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

In [73]:
#It shows the images of different cards